all:
  vars:
    mssql_pid: 'Evaluation'
    mssql_accept_eula: true
    mssql_pcs_cluster_vip_cidr: ''
    system_upgrade_all_packages: true
    system_hosts_file_create: true
    system_hosts_file_disable_entries: ['127.0.1.1']
    system_firewall_disable: true
    system_selinux_disable: true
    system_extend_os_lvm: true
    system_mount_data_disks: true
    system_data_disks_filesystem: 'xfs'
    system_data_disk_mount_paths: ['/sqlnux']
    system_create_account: true
    system_create_account_username: vmware
    system_create_account_password: vmware
